### ISSUE TITLE
RLA v2 Logs Test

### ISSUE THREAD

**Issue by TimNN** [TimNN/rla-test#2]

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/367727129) ([raw log](https://api.travis-ci.org/v3/job/367727129/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Check compiletest suite=ui mode=ui (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:42:39] 
[00:42:39] running 1361 tests
[00:42:45] .................................................................................i..................
[00:42:51] ..................F.....i...........................................................................
[00:42:58] ....................................................................................................
[00:43:02] ....................................................................................................
[00:43:07] ....................................................................................................
[00:43:13] ....................................................................................................
---
[00:43:56] 
[00:43:56] ---- [ui] ui/const-fn-error.rs stdout ----
[00:43:56]  diff of stderr:
[00:43:56] 
[00:43:56] 4 LL |     let mut sum = 0;
[00:43:56] 6 
[00:43:56] 6 
[00:43:56] - error[E0015]: calls in constant functions are limited to constant functions, struct and enum constructors
[00:43:56] + error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
[00:43:56] 9    |
[00:43:56] 9    |
[00:43:56] 10 LL |     for i in 0..x {
[00:43:56] 
[00:43:56] The actual stderr differed from the expected stderr.
[00:43:56] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/const-fn-error.stderr
[00:43:56] To update references, run this command from build directory:
[00:43:56] To update references, run this command from build directory:
[00:43:56] /checkout/src/test/ui/update-references.sh '/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui' 'const-fn-error.rs'
[00:43:56] error: 1 errors occurred comparing output.
[00:43:56] status: exit code: 101
[00:43:56] status: exit code: 101
[00:43:56] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/const-fn-error.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/const-fn-error.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/const-fn-error.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[00:43:56] ------------------------------------------
[00:43:56] 
[00:43:56] ------------------------------------------
[00:43:56] stderr:
[00:43:56] stderr:
[00:43:56] ------------------------------------------
[00:43:56] {"message":"blocks in constant functions are limited to items and tail expressions","code":{"code":"E0016","explanation":"\nBlocks in constants may only contain items (such as constant, function\ndefinition, etc...) and a tail expression. Erroneous code example:\n\n```compile_fail,E0016\nconst FOO: i32 = { let x = 0; x }; // 'x' isn't an item!\n```\n\nTo avoid it, you have to replace the non-item object:\n\n```\nconst FOO: i32 = { const X : i32 = 0; X };\n```\n"},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":562,"byte_end":563,"line_start":16,"line_end":16,"column_start":19,"column_end":20,"is_primary":true,"text":[{"text":"    let mut sum = 0;","highlight_start":19,"highlight_end":20}],"label":null,"suggested_replacement":null,"expansion":null}],"children":[],"rendered":"error[E0016]: blocks in constant functions are limited to items and tail expressions\n  --> /checkout/src/test/ui/const-fn-error.rs:16:19\n   |\nLL |     let mut sum = 0;\n   |                   ^\n\n"}
[00:43:56] {"message":"calls in constant functions are limited to constant functions, tuple structs and tuple variants","code":{"code":"E0015","explanation":"\nThe only functions that can be called in static or constant expressions are\n`const` functions, and struct/enum constructors. `const` functions are only\navailable on a nightly compiler. Rust currently does not support more general\ncompile-time function execution.\n\n```\nconst FOO: Option<u8> = Some(1); // enum constructor\nstruct Bar {x: u8}\nconst BAR: Bar = Bar {x: 1}; // struct constructor\n```\n\nSee [RFC 911] for more details on the design of `const fn`s.\n\n[RFC 911]: https://github.com/rust-lang/rfcs/blob/master/text/0911-const-fn.md\n"},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":599,"byte_end":603,"line_start":18,"line_end":18,"column_start":14,"column_end":18,"is_primary":true,"text":[{"text":"    for i in 0..x {","highlight_start":14,"highlight_end":18}],"label":null,"suggested_replacement":null,"expansion":{"span":{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":599,"byte_end":603,"line_start":18,"line_end":18,"column_start":14,"column_end":18,"is_primary":false,"text":[{"text":"    for i in 0..x {","highlight_start":14,"highlight_end":18}],"label":null,"suggested_replacement":null,"expansion":null},"macro_decl_name":"desugaring of `...`","def_site_span":{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":599,"byte_end":603,"line_start":18,"line_end":18,"column_start":14,"column_end":18,"is_primary":false,"text":[{"text":"    for i in 0..x {","highlight_start":14,"highlight_end":18}],"label":null,"suggested_replacement":null,"expansion":null}}}],"children":[],"rendered":"error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants\n  --> /checkout/src/test/ui/const-fn-error.rs:18:14\n   |\nLL |     for i in 0..x {\n   |              ^^^^\n\n"}
[00:43:56] {"message":"constant function contains unimplemented expression type","code":{"code":"E0019","explanation":"\nA function call isn't allowed in the const's initialization expression\nbecause the expression's value must be known at compile-time. Erroneous code\nexample:\n\n```compile_fail\nenum Test {\n    V1\n}\n\nimpl Test {\n    fn test(&self) -> i32 {\n        12\n    }\n}\n\nfn main() {\n    const FOO: Test = Test::V1;\n\n    const A: i32 = FOO.test(); // You can't call Test::func() here!\n}\n```\n\nRemember: you can't use a function call inside a const's initialization\nexpression! However, you can totally use it anywhere else:\n\n```\nenum Test {\n    V1\n}\n\nimpl Test {\n    fn func(&self) -> i32 {\n        12\n    }\n}\n\nfn main() {\n    const FOO: Test = Test::V1;\n\n    FOO.func(); // here is good\n    let x = FOO.func(); // or even here!\n}\n```\n"},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":599,"byte_end":603,"line_start":18,"line_end":18,"column_start":14,"column_end":18,"is_primary":true,"text":[{"text":"    for i in 0..x {","highlight_start":14,"highlight_end":18}],"label":null,"suggested_replacement":null,"expansion":{"span":{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":599,"byte_end":603,"line_start":18,"line_end":18,"column_start":14,"column_end":18,"is_primary":false,"text":[{"text":"    for i in 0..x {","highlight_start":14,"highlight_end":18}],"label":null,"suggested_replacement":null,"expansion":null},"macro_decl_name":"desugaring of `...`","def_site_span":{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":599,"byte_end":603,"line_start":18,"line_end":18,"column_start":14,"column_end":18,"is_primary":false,"text":[{"text":"    for i in 0..x {","highlight_start":14,"highlight_end":18}],"label":null,"suggested_replacement":null,"expansion":null}}}],"children":[],"rendered":"error[E0019]: constant function contains unimplemented expression type\n  --> /checkout/src/test/ui/const-fn-error.rs:18:14\n   |\nLL |     for i in 0..x {\n   |              ^^^^\n\n"}
[00:43:56] {"message":"constant evaluation error","code":{"code":"E0080","explanation":"\nThis error indicates that the compiler was unable to sensibly evaluate an\nconstant expression that had to be evaluated. Attempting to divide by 0\nor causing integer overflow are two ways to induce this error. For example:\n\n```compile_fail,E0080\nenum Enum {\n    X = (1 << 500),\n    Y = (1 / 0)\n}\n```\n\nEnsure that the expressions given can be evaluated as the desired integer type.\nSee the FFI section of the Reference for more information about using a custom\ninteger type:\n\nhttps://doc.rust-lang.org/reference.html#ffi-attributes\n"},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":599,"byte_end":603,"line_start":18,"line_end":18,"column_start":14,"column_end":18,"is_primary":true,"text":[{"text":"    for i in 0..x {","highlight_start":14,"highlight_end":18}],"label":"calling non-const fn `<I as std::iter::IntoIterator><std::ops::Range<usize>>::into_iter`","suggested_replacement":null,"expansion":{"span":{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":599,"byte_end":603,"line_start":18,"line_end":18,"column_start":14,"column_end":18,"is_primary":false,"text":[{"text":"    for i in 0..x {","highlight_start":14,"highlight_end":18}],"label":null,"suggested_replacement":null,"expansion":null},"macro_decl_name":"desugaring of `...`","def_site_span":{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":599,"byte_end":603,"line_start":18,"line_end":18,"column_start":14,"column_end":18,"is_primary":false,"text":[{"text":"    for i in 0..x {","highlight_start":14,"highlight_end":18}],"label":null,"suggested_replacement":null,"expansion":null}}},{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":773,"byte_end":777,"line_start":29,"line_end":29,"column_start":19,"column_end":23,"is_primary":false,"text":[{"text":"    let a : [i32; f(X)];","highlight_start":19,"highlight_end":23}],"label":"inside call to `f`","suggested_replacement":null,"expansion":null}],"children":[{"message":"for constant expression here","code":null,"level":"note","spans":[{"file_name":"/checkout/src/test/ui/const-fn-error.rs","byte_start":767,"byte_end":778,"line_start":29,"line_end":29,"column_start":13,"column_end":24,"is_primary":true,"text":[{"text":"    let a : [i32; f(X)];","highlight_start":13,"highlight_end":24}],"label":null,"suggested_replacement":null,"expansion":null}],"children":[],"rendered":null}],"rendered":"error[E0080]: constant evaluation error\n  --> /checkout/src/test/ui/const-fn-error.rs:18:14\n   |\nLL |     for i in 0..x {\n   |              ^^^^ calling non-const fn `<I as std::iter::IntoIterator><std::ops::Range<usize>>::into_iter`\n...\nLL |     let a : [i32; f(X)];\n   |                   ---- inside call to `f`\n   |\nnote: for constant expression here\n  --> /checkout/src/test/ui/const-fn-error.rs:29:13\n   |\nLL |     let a : [i32; f(X)];\n   |             ^^^^^^^^^^^\n\n"}
[00:43:56] {"message":"aborting due to 4 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to 4 previous errors\n\n"}
[00:43:56] {"message":"Some errors occurred: E0015, E0016, E0019, E0080.","code":null,"level":"","spans":[],"children":[],"rendered":"Some errors occurred: E0015, E0016, E0019, E0080.\n"}
[00:43:56] {"message":"For more information about an error, try `rustc --explain E0015`.","code":null,"level":"","spans":[],"children":[],"rendered":"For more information about an error, try `rustc --explain E0015`.\n"}
[00:43:56] ------------------------------------------
[00:43:56] 
[00:43:56] thread '[ui] ui/const-fn-error.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2930:9
[00:43:56] note: Run with `RUST_BACKTRACE=1` for a backtrace.
---
[00:43:56] 
[00:43:56] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:488:22
[00:43:56] 
[00:43:56] 
[00:43:56] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:43:56] 
[00:43:56] 
[00:43:56] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:43:56] Build completed unsuccessfully in 0:02:23
[00:43:56] Build completed unsuccessfully in 0:02:23
[00:43:56] Makefile:58: recipe for target 'check' failed
[00:43:56] make: *** [check] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:010a2be7
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/367703353) ([raw log](https://api.travis-ci.org/v3/job/367703353/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:42:34] Documenting book redirect pages (x86_64-unknown-linux-gnu)
[00:42:35] Documenting stage2 std (x86_64-unknown-linux-gnu)
[00:42:35]    Compiling core v0.0.0 (file:///checkout/src/libcore)
[00:42:35]  Documenting core v0.0.0 (file:///checkout/src/libcore)
[00:42:45] thread 'main' panicked at 'assertion failed: *old == value', librustc_data_structures/sync.rs:241:42
[00:42:46] error: Could not compile `core`.
[00:42:46] warning: build failed, waiting for other jobs to finish...
[00:43:25] warning: [1] cannot be resolved, ignoring it...
[00:43:25] 
---
[00:43:28] 
[00:43:33] error: build failed
[00:43:33] 
[00:43:33] 
[00:43:33] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "doc" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--no-deps" "-p" "alloc" "-p" "core" "-p" "std" "-p" "std_unicode"
[00:43:33] 
[00:43:33] 
[00:43:33] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap doc
[00:43:33] Build completed unsuccessfully in 0:05:47
[00:43:33] Build completed unsuccessfully in 0:05:47
[00:43:33] make: *** [all] Error 1
[00:43:33] Makefile:28: recipe for target 'all' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:033e987b
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))
